### ISSUE TITLE
DM Fleet pings

### ISSUE THREAD

**Issue by CokkocZateki** [ppfeufer/aa-fleetpings#139]
Would be nice to be able to clear up the our Discord server. Have the ability to be able to DM Fleet pings to a selected states in AA so that members can decide to mute or not

**Comment by ppfeufer** [comment]
And flooding the Discord API with DM requests to potentially hundreds of users simultaneously? That's one way to get your bot banned by Discord …

**Comment by CokkocZateki** [comment]
That is true. How it plays in my head is if our Alliance wants to send out a CTA notification. Instead of spamming a channel users in the opt in group could rather get it sent to them as a DM? Not too sure on the know how or technical side but i have seen some groups do that

**Comment by ppfeufer** [comment]
Sure, you can work around or rather with Discord's rate limit. AA does that for the model updates and so on. But depending on how large the group is, that needs to get the DMs, this can take quite a while until all have them, in which time the OP could already be over.

In other words, I don't see a viable solution to get the DMs to all group members in a reliable way. At least not without hammering the Discord API hoping it gets through without being banned at some point.

If you want to notify a larger number of users on Discord, you better do that in a channel instead of spamming the same message to potentially hundreds of people as DM, which will likely also be detected by Discord as a spam attempt by a bot and likely get your bot banned.

**Comment by CokkocZateki** [comment]
I agree with you. Too risky and too much dancing around the fire.
