### ISSUE TITLE
Add a setting to use directly doctrines from fittings plugin

### ISSUE THREAD

**Issue by huideaki** [ppfeufer/aa-fleetpings#6]
Add a setting that would change the frontend drop down to fetch from fittings plugin without having to create new doctrines in auth with this plugin.

**Comment by ppfeufer** [comment]
Nice idea, thanks for bringing this up. But as discussed in Discord, this could prove difficult, since the doctrines in the `fittings` app could turn out to be restricted to certain groups.

I put this in low prio for now, in case I git an idea without having to rebuild the permission system of the `fleet` app.
