### ISSUE TITLE
[Feature Request] Allow for additional custom ping targets

### ISSUE THREAD

**Issue by Valiantiam** [ppfeufer/aa-fleetpings#85]
### Context

Currently the app only supports pinging targets that are groups. It does not support custom discord roleIDs or states (which are also auto synced as groups to discord)

### Describe the feature you have in mind

In the ping targets configuration, you should have the option to see states as a choice of roles to pick from, as well as _potentially_ a way to have a custom discord roleID you would like pinged.

### Additional context

My main group of members use the state "Corp Member" (renamed from member) as all their base roles throughout 3rd party tools. (Discord, wikijs, etc)

The app however only currently lets me select from groups themselves, even though states are essentially treated as groups by every other external 3rd party app such as discord.

**Comment by ppfeufer** [comment]
Hey there,

Thanks for the suggestion, but I have to decline, unfortunately.

Ping targets in form of states vs. groups is an either/or situation here. In other words, they have to be mutually exclusive, so that a defined ping target can not be a group and a state at the same time. I currently see no option to achieve this with how the Django models are designed. Also, it raises the question of which one of both is the "leading" setting. Does "state" override "group" when set or the other way around?

On external services like Discord or Mumble they are both treated as the same because these services do not distinguish between the both of them, AA does. So the decision was made to go with "groups" here since they have potentially more targets and are more finely divided and allow a more granular selection.

A workaround would be to use the "[Auto Groups](https://allianceauth.readthedocs.io/en/latest/features/apps/autogroups.html)" app which is bundled with AA to create corp/alliance groups you then can select as ping targets.
